In [2]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent

import pandas as pd

pd.set_option('display.max_columns', None)  # none은 제한값 자리(몇개 열까지 보여줄까)
pd.set_option('display.max_rows', None)

# ============================================================
# 0. 데이터 불러오기: 2-5 train_test_comparison에서 제거된 이상치까지 반영된 데이터셋
# ============================================================

train_kf_oof = pd.read_parquet(PROJECT_ROOT / 'parqueted_data' / '0_kf_oof_train.parquet')

print(train_kf_oof.shape)

from sklearn import set_config
set_config(display='text')
# scikit-learn의 HTML 출력 과정에서 발생한 cp949 간 UTF-8 충돌 때문에 넣는 코드

(616293, 40)

In [10]:
# ============================================================
# 1. 전체 OOF 종속변수 구간별 RMSE 분석
# ============================================================

import numpy as np

# 종속변수 분위수 기준으로 구간 설정
quantiles = [0, 0.5, 0.75, 0.9, 0.95, 0.99, 1.0]
labels = ['0~50%', '50~75%', '75~90%', '90~95%', '95~99%', '99~100%']

train_kf_oof['y_kf_val_quant'] = pd.qcut(  # pd.qcut() 지정한 분위수 경계값 기준으로 구간 나눠줌
    train_kf_oof['y_kf_val'],  # 매개변수: 구간 나눌 데이터
    q=quantiles,  # 매개변수: 구간을 나눌 위치(분위수)
    labels=labels # 매개변수: 각각의 라벨(q보다 하나 적어야 함)
)

# 구간별 RMSE 계산
y_kf_val_segment_rmse = (
    train_kf_oof
    .groupby('y_kf_val_quant', observed=True)  # observed=True: 관측된 행만 기재(count가 0인 행은 제거)
    .agg(
        count=('resid_sq', 'size'),
        mse=('resid_sq', 'mean'),  # 잔차제곱의 평균 = mse, 루트하면 rmse
        resid_sq_sum=('resid_sq', 'sum')
    )
)

y_kf_val_segment_rmse['rmse'] = np.sqrt(y_kf_val_segment_rmse['mse'])
y_kf_val_segment_rmse['resid_sq_sum_contribution_pct(%)'] = (
    y_kf_val_segment_rmse['resid_sq_sum']/
    y_kf_val_segment_rmse['resid_sq_sum'].sum()
    *100
)

display(y_kf_val_segment_rmse[['count', 'rmse', 'resid_sq_sum','resid_sq_sum_contribution_pct(%)']])

,count,rmse,resid_sq_sum,resid_sq_sum_contribution_pct(%)
y_kf_val_quant,,,,
0~50%,340940,0.096568,3179.427499,9.516899
50~75%,127705,0.094845,1148.784463,3.438627
75~90%,87488,0.157642,2174.173762,6.507899
90~95%,29345,0.280564,2309.926209,6.914243
95~99%,24674,0.655039,10587.012558,31.689834
99~100%,6141,1.510367,14008.905566,41.932498

In [17]:
# ============================================================
# 2. Fold별 종속변수 구간별 RMSE 분석
# ============================================================

# Fold별, 종속변수 구간별 RMSE 계산
fold_segment_rmse = (
    train_kf_oof
    .groupby(['fold_num', 'y_kf_val_quant'], observed=True)
    .agg(
        count=('resid_sq', 'size'),
        mse=('resid_sq', 'mean')
    )
)

fold_segment_rmse['rmse'] = np.sqrt(fold_segment_rmse['mse'])

# Fold별 RMSE 비교표
fold_segment_rmse_pivot = fold_segment_rmse['rmse'].unstack('fold_num')

display(fold_segment_rmse_pivot)

fold_num               1         2         3         4         5
y_kf_val_quant
0~50%           0.126872  0.084618  0.087797  0.086416  0.089836
50~75%          0.118810  0.091043  0.087636  0.090398  0.089004
75~90%          0.189627  0.148832  0.141992  0.160345  0.141922
90~95%          0.316162  0.275802  0.263280  0.270517  0.261576
95~99%          0.697080  0.546779  0.641688  0.678735  0.625992
99~100%         1.453365  0.816463  1.568512  1.899016  1.374769

In [19]:
train_kf_oof.head(20)

,timestamp,station_id,wl_t,wl_t_minus_1h,wl_t_minus_3h,wl_t_minus_6h,wl_t_minus_12h,wl_t_minus_24h,imerg_rain_1h,imerg_rain_6h,imerg_rain_24h,sfc_rain_1h,sfc_rain_6h,sfc_rain_24h,radar_reflectivity_mean,radar_reflectivity_p95,radar_reflectivity_ge20_fraction,cat_area,wsarea,mean_elevation,mean_slope,urban_ratio,forest_ratio,stream_order,target_maxrise_6h,event_id,wl_diff_1h,wl_diff_3h,wl_diff_6h,wl_diff_12h,wl_diff_24h,imerg_int_1to6h,imerg_int_6to24h,sfc_int_1to6h,sfc_int_6to24h,y_kf_val,y_kf_pred,resid,resid_sq,fold_num,y_kf_val_quant
0,2100-01-01,ST0001,0.29,0.29,0.28,0.28,0.28,0.27,0.000,0.000,0.000,0.0,0.0,0.0,12.162,25.274,0.1445,2.8605,37.0279,124.37,9.6147,11.1141,52.4597,1.9592,0.00,1,0.00,0.01,0.01,0.01,0.02,0.0000,0.000000,0.00,0.000000,0.00,0.024048,-0.024048,0.000578,5,0~50%
1,2100-01-01,ST0002,0.77,0.76,0.77,0.77,0.76,0.77,0.000,0.000,0.000,0.0,0.0,0.0,0.912,12.060,0.0000,3.9564,42.8163,180.09,16.5687,2.5710,88.0622,1.8000,0.00,1,0.01,0.00,0.00,0.01,0.00,0.0000,0.000000,0.00,0.000000,0.00,0.003616,-0.003616,0.000013,5,0~50%
2,2100-01-01,ST0003,0.73,0.73,0.74,0.74,0.73,0.73,0.000,0.000,0.000,0.0,0.0,0.0,18.060,30.920,0.5654,4.2240,80.8559,125.04,12.1864,34.3816,56.6211,2.2500,0.00,1,0.00,-0.01,-0.01,0.00,0.00,0.0000,0.000000,0.00,0.000000,0.00,0.014925,-0.014925,0.000223,5,0~50%
3,2100-01-01,ST0004,1.01,1.01,1.01,1.01,1.01,1.01,0.000,0.000,0.000,0.0,0.0,0.0,0.029,0.000,0.0000,3.2098,252.5946,199.30,13.5951,2.7206,73.1707,2.1207,0.00,1,0.00,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.000000,0.00,-0.005762,0.005762,0.000033,5,0~50%
4,2100-01-01,ST0005,1.01,1.01,1.01,1.01,1.03,1.06,3.018,7.493,7.497,0.0,0.0,0.0,6.898,21.500,0.0811,3.6470,118.5237,246.72,17.1248,0.4779,88.0002,2.0000,0.03,1,0.00,0.00,0.00,-0.02,-0.05,0.8950,0.000222,0.00,0.000000,0.03,0.039088,-0.009088,0.000083,5,50~75%
5,2100-01-01,ST0006,0.75,0.75,0.74,0.77,0.73,0.88,0.000,0.144,0.146,0.0,2.0,2.0,15.808,21.178,0.0811,11.8928,14.9987,38.11,5.7671,63.7535,18.7559,1.2222,0.08,1,0.00,0.01,-0.02,0.02,-0.13,0.0288,0.000111,0.40,0.000000,0.08,0.105763,-0.025763,0.000664,5,75~90%
6,2100-01-01,ST0007,1.58,1.58,1.58,1.58,1.60,1.64,2.621,4.574,6.215,0.0,2.0,2.0,19.108,27.750,0.3613,2.9860,99.0096,335.78,16.2836,1.0168,87.6109,2.0588,0.00,1,0.00,0.00,0.00,-0.02,-0.06,0.3906,0.091167,0.40,0.000000,0.00,0.079097,-0.079097,0.006256,5,0~50%
7,2100-01-01,ST0008,122.99,123.00,122.98,122.97,123.00,123.00,1.496,15.696,16.742,0.0,0.0,0.0,21.069,24.540,0.7139,6.0509,993.3904,274.74,16.9880,0.9004,81.7343,2.4133,0.03,1,-0.01,0.01,0.02,-0.01,-0.01,2.8400,0.058111,0.00,0.000000,0.03,-0.024613,0.054613,0.002983,5,50~75%
8,2100-01-01,ST0009,1.41,1.41,1.42,1.42,1.43,1.45,0.125,0.184,0.184,0.0,0.0,0.0,0.039,0.000,0.0000,3.7874,87.1406,45.85,5.5734,12.3710,18.9725,2.0370,0.00,1,0.00,-0.01,-0.01,-0.02,-0.04,0.0118,0.000000,0.00,0.000000,0.00,0.018924,-0.018924,0.000358,5,0~50%
9,2100-01-01,ST0010,1.68,1.69,1.71,1.74,1.80,1.32,0.000,0.013,0.121,0.0,0.0,0.0,0.000,0.000,0.0000,3.4582,934.2290,501.16,23.1930,2.9555,88.8847,2.2703,-0.01,1,-0.01,-0.03,-0.06,-0.12,0.36,0.0026,0.006000,0.00,0.000000,-0.01,0.017734,-0.027734,0.000769,5,0~50%
10,2100-01-01,ST0011,0.97,0.93,0.89,0.90,0.91,0.95,0.000,0.000,0.000,0.0,7.0,7.0,1.536,13.680,0.0088,3.6128,23.0961,164.23,10.2866,4.8419,60.3150,1.8108,0.00,1,0.04,0.08,0.07,0.06,0.02,0.0000,0.000000,1.40,0.000000,0.00,0.073676,-0.073676,0.005428,5,0~50%
11,2100-01-01,ST0012,2.30,2.30,2.30,2.28,2.29,2.28,0.000,0.000,0.000,0.0,0.0,0.0,19.826,32.662,0.4814,3.1096,35.6979,148.87,13.8923,8.0977,70.3359,1.8039,0.01,1,0.00,0.00,0.02,0.01,0.02,0.0000,0.000000,0.00,0.000000,0.01,0.016154,-0.006154,0.000038,5,0~50%
12,2100-01-01,ST0013,1.07,1.06,1.02,0.99,0.89,0.99,0.000,0.000,0.000,0.0,0.0,0.0,0.034,0.000,0.0000,4.6532,172.5370,51.28,5.2532,29.8408,23.1837,2.2500,0.04,1,0.01,0.05,0.08,0.18,0.08,0.0000,0.000000,0.00,0.000000,0.04,0.038649,0.001351,0.000002,5,50~75%
13,2100-01-01,ST0014,1.49,1.49,1.49,1.49,1.50,1.52,1.241,16.670,17.502,0.5,0.9,0.9,3.770,15.400,0.0000,3.0176,27.0666,482.70,18.3081,5.2857,86.6912,1.7255,0.00,1,0.00,0.00,0.00,-0.01,-0.03,3.0858,0.046222,0.08,0.000000,0.00,-0.001443,0.001443,0.000002,5,0~50%
14,2100-01-01,ST0015,0.68,0.68,0.68,0.69,0.70,0.76,6.014,19.092,19.738,0.0,0.0,0.0,1.770,17.056,0.0068,3.6475,209.5924,231.16,14.3766,1.4500,81.3616,2.3922,0.00,1,0.00,0.00,-0.01,-0.02,-0.08,2.6156,0.035889,0.00,0.000000,0.00,0.044351,-0.044351,0.001967,5,0~50%
15,2100-01-01,ST0016,0.54,0.53,0.54,0.37,0.41,0.49,0.606,2.429,2.459,0.0,64.0,64.0,20.710,25.774,0.5703,3.4314,1904.1982,103.48,8.6120,3.4848,46.2649,2.6667,0.40,1,0.01,0.00,0.17,0.13,0.05,0.3646,0.001667,12.80,0.000000,0.40,0.233103,0.166897,0.027855,5,90~95%
16,2100-01-01,ST0017,0.50,0.50,0.50,0.50,0.50,0.51,3.598,6.602,6.613,0.0,1.5,1.5,1.295,11.998,0.0000,2.9548,27.4837,126.80,10.1934,38.5445,52.4014,1.9000,0.26,1,0.00,0.00,0.00,0.00,-0.01,0.6008,0.000611,0.30,0.000000,0.26,0.079478,0.180522,0.032588,5,75~90%
17,2100-01-01,ST0018,0.67,0.67,0.66,0.66,0.67,0.69,0.003,0.003,0.003,0.0,0.0,0.0,14.920,17.360,0.0000,3.1672,22.6316,82.11,8.0292,14.6989,37.9430,1.6818,0.00,1,0.00,0.01,0.01,0.00,-0.02,0.0000,0.000000,0.00,0.000000,0.00,0.025474,-0.025474,0.000649,5,0~50%
18,2100-01-01,ST0019,1.32,1.32,1.32,1.33,1.28,1.29,0.033,7.187,8.372,0.0,6.5,12.0,7.659,16.080,0.0020,3.2244,30.3500,325.87,14.4071,4.0537,75.4045,1.6226,0.00,1,0.00,0.00,-0.01,0.04,0.03,1.4308,0.065833,1.30,0.305556,0.00,0.014521,-0.014521,0.000211,5,0~50%
19,2100-01-01,ST0020,0.23,0.24,0.24,0.24,0.24,0.26,0.019,0.416,0.841,1.3,4.7,4.7,12.463,24.337,0.2354,2.8981,38.4984,266.21,13.7094,12.8444,73.2404,1.9231,0.01,1,-0.01,-0.01,-0.01,-0.01,-0.03,0.0794,0.023611,0.68,0.000000,0.01,0.036025,-0.026025,0.000677,5,0~50%

In [22]:
# ============================================================
# 4. 종속변수 상위 5% 구간의 고잔차 데이터 분석
# ============================================================

# 종속변수 상위 5% 데이터 추출
high_y_resid = train_kf_oof.loc[
    train_kf_oof['y_kf_val_quant'].isin(['95~99%', '99~100%'])
].copy()

# 제곱잔차 기준 내림차순 정렬
high_y_error = high_y_resid.sort_values(
    'resid_sq', ascending=False
)

# # 주요 컬럼 확인
# display(
#     high_y_error[
#         ['fold', 'station_id', 'y_kf_val', 'y_kf_pred',
#          'residual', 'residual_sq']
#     ]
# )

display(high_y_error['station_id'].value_counts())

station_id
ST0358    830
ST0326    812
ST0292    810
ST0159    780
ST0347    750
ST0110    679
ST0313    637
ST0415    437
ST0234    334
ST0130    286
ST0275    274
ST0129    272
ST0067    265
ST0192    241
ST0051    228
ST0380    206
ST0335    193
ST0164    190
ST0178    169
ST0282    168
ST0028    166
ST0310    165
ST0388    163
ST0221    158
ST0062    149
ST0149    148
ST0354    145
ST0332    142
ST0297    141
ST0148    133
ST0353    132
ST0393    132
ST0194    130
ST0095    129
ST0428    128
ST0357    127
ST0397    125
ST0356    125
ST0116    125
ST0424    123
ST0272    123
ST0059    122
ST0318    115
ST0242    114
ST0336    113
ST0226    111
ST0323    111
ST0013    110
ST0040    109
ST0036    109
ST0073    109
ST0435    105
ST0006    103
ST0301    103
ST0268    102
ST0258    102
ST0303    101
ST0125    100
ST0207    100
ST0093     96
ST0312     96
ST0337     95
ST0084     94
ST0368     93
ST0260     93
ST0092     93
ST0413     92
ST0101     92
ST0152     91
ST0007     90
ST0345     90
ST0426     90
ST0183     89
ST0391     88
ST0238     88
ST0156     87
ST0161     86
ST0444     86
ST0211     85
ST0127     85
ST0212     84
ST0191     84
ST0075     83
ST0450     83
ST0071     83
ST0448     82
ST0087     82
ST0382     82
ST0001     82
ST0329     82
ST0217     82
ST0283     81
ST0162     81
ST0327     81
ST0018     81
ST0172     81
ST0079     81
ST0433     80
ST0064     80
ST0160     79
ST0438     79
ST0299     78
ST0220     78
ST0265     78
ST0219     78
ST0339     77
ST0240     77
ST0246     77
ST0046     76
ST0300     76
ST0271     76
ST0284     75
ST0143     75
ST0157     75
ST0296     75
ST0412     75
ST0017     74
ST0112     74
ST0080     74
ST0103     74
ST0416     74
ST0141     74
ST0343     73
ST0117     73
ST0039     73
ST0131     72
ST0175     72
ST0204     72
ST0224     72
ST0010     71
ST0214     71
ST0395     71
ST0050     70
ST0372     70
ST0228     70
ST0304     69
ST0319     69
ST0340     69
ST0180     69
ST0005     69
ST0278     69
ST0434     68
ST0252     67
ST0445     67
ST0034     66
ST0317     66
ST0102     66
ST0379     65
ST0293     65
ST0030     65
ST0205     64
ST0163     64
ST0400     64
ST0208     64
ST0459     63
ST0237     63
ST0364     63
ST0273     63
ST0276     62
ST0231     62
ST0229     62
ST0447     61
ST0069     61
ST0410     60
ST0086     60
ST0015     60
ST0446     59
ST0187     59
ST0462     59
ST0170     59
ST0098     58
ST0043     58
ST0115     58
ST0024     58
ST0038     58
ST0009     58
ST0352     57
ST0334     57
ST0374     57
ST0316     57
ST0403     57
ST0022     56
ST0128     56
ST0113     56
ST0076     56
ST0114     56
ST0451     55
ST0461     55
ST0171     55
ST0409     55
ST0250     55
ST0167     54
ST0186     54
ST0181     54
ST0455     54
ST0035     53
ST0122     53
ST0154     53
ST0390     53
ST0189     52
ST0289     52
ST0302     52
ST0405     51
ST0083     51
ST0254     51
ST0298     51
ST0065     51
ST0396     51
ST0153     51
ST0016     50
ST0257     50
ST0452     50
ST0308     49
ST0401     49
ST0029     49
ST0048     49
ST0432     49
ST0243     48
ST0056     48
ST0140     48
ST0385     48
ST0068     47
ST0173     47
ST0108     47
ST0223     47
ST0392     47
ST0166     47
ST0274     47
ST0235     47
ST0386     46
ST0398     46
ST0041     46
ST0248     45
ST0023     45
ST0213     45
ST0026     45
ST0139     45
ST0465     44
ST0419     44
ST0037     44
ST0295     44
ST0421     44
ST0315     44
ST0241     43
ST0150     43
ST0367     43
ST0346     43
ST0259     43
ST0215     43
ST0328     43
ST0168     43
ST0232     42
ST0066     42
ST0138     41
ST0320     41
ST0008     41
ST0402     41
ST0134     41
ST0411     40
ST0165     40
ST0423     40
ST0239     40
ST0269     40
ST0363     40
ST0381     40
ST0078     39
ST0389     39
ST0280     39
ST0458     39
ST0439     39
ST0262     39
ST0349     39
ST0251     38
ST0063     38
ST0099     38
ST0394     38
ST0120     38
ST0185     37
ST0011     37
ST0406     37
ST0136     37
ST0106     37
ST0351     37
ST0427     37
ST0135     36
ST0210     36
ST0045     36
ST0074     36
ST0361     36
ST0109     36
ST0201     36
ST0362     36
ST0196     35
ST0111     35
ST0331     35
ST0429     35
ST0341     34
ST0179     34
ST0227     34
ST0142     34
ST0014     33
ST0081     33
ST0375     33
ST0294     33
ST0124     33
ST0070     32
ST0464     32
ST0287     32
ST0463     32
ST0383     31
ST0184     31
ST0057     31
ST0443     31
ST0123     30
ST0449     30
ST0441     30
ST0193     30
ST0218     30
ST0236     30
ST0118     30
ST0255     30
ST0044     30
ST0291     30
ST0404     29
ST0261     29
ST0233     29
ST0249     29
ST0020     29
ST0147     29
ST0414     29
ST0457     29
ST0453     29
ST0285     28
ST0355     28
ST0431     28
ST0311     28
ST0247     28
ST0267     28
ST0003     27
ST0053     27
ST0344     27
ST0256     27
ST0085     27
ST0090     27
ST0420     27
ST0100     27
ST0169     27
ST0225     27
ST0418     27
ST0126     26
ST0384     26
ST0306     26
ST0376     26
ST0121     26
ST0097     25
ST0137     25
ST0369     25
ST0454     25
ST0371     25
ST0321     25
ST0182     24
ST0105     24
ST0206     24
ST0377     24
ST0203     24
ST0422     24
ST0348     24
ST0031     24
ST0264     24
ST0202     24
ST0188     24
ST0437     24
ST0378     24
ST0360     24
ST0133     23
ST0146     23
ST0370     22
ST0279     22
ST0151     22
ST0104     22
ST0144     22
ST0425     21
ST0096     21
ST0324     20
ST0253     20
ST0399     20
ST0033     20
ST0058     19
ST0244     19
ST0325     19
ST0281     18
ST0430     18
ST0263     18
ST0002     18
ST0198     17
ST0042     17
ST0359     17
ST0132     16
ST0330     16
ST0373     16
ST0072     16
ST0025     16
ST0407     15
ST0290     15
ST0338     15
ST0314     14
ST0061     14
ST0060     14
ST0456     14
ST0366     14
ST0200     14
ST0119     14
ST0145     14
ST0077     13
ST0155     13
ST0342     13
ST0230     13
ST0107     13
ST0089     12
ST0209     12
ST0270     12
ST0286     12
ST0365     12
ST0216     12
ST0012     11
ST0417     11
ST0054     11
ST0088     11
ST0440     11
ST0387     11
ST0195     11
ST0176     10
ST0197     10
ST0004     10
ST0047      9
ST0408      9
ST0305      9
ST0199      9
ST0052      8
ST0309      8
ST0288      7
ST0091      6
ST0049      6
ST0158      5
ST0055      5
ST0082      5
ST0460      5
ST0245      5
ST0094      4
ST0190      4
ST0021      4
ST0350      3
ST0032      3
ST0322      1
ST0333      1
ST0019      1
Name: count, dtype: int64